[main]
dev_run = false
data = "data/"

[sbatch]
job_name = "chempipe"
account = "loni_username"
partition = "workq"
nodes = 1
ntasks = 48
time = "06:00:00"
email_user = "username@tulane.edu"
email_type = "END"

[potential]
model_path = "/home/$USER/chem-pipe/pretrained/mattersim-v1.0.0-1M.pth"
fmax = 0.01

[vasp]
script = "vasp_std"

[vasp.settings]
# KPOINTS
gamma = true       # Gamma-centered k-points, otherwise Monkhorst-Pack
kpts = [10, 10, 1]

# INCAR
algo = "VeryFast"
amix = 0.2
amix_mag = 0.8
bmix = 1e-5
bmix_mag = 1e-5
ediff = 1e-5
ediffg = -0.03
encut = 400.0
gga = "PE"
ibrion = 3
idipol = 0
ismear = 2
ivdw = 2
laechg = false
lcharg = false
lorbit = false
lreal = "Auto"
lvtot = false
lwave = false
nelmin = 5
nsw = 10          # Number of fine-tuning samples
nwrite = 1
potim = 0.15
prec = "Accurate"
sigma = 0.2
ncore = 4
kpar = 2
